package myclaw.session;

public enum SessionEventType {
    SESSION_CREATED,
    USER_MESSAGE_ADDED,
    BACKEND_SELECTED,
    BACKEND_REQUEST_STARTED,
    ASSISTANT_MESSAGE_ADDED,
    BACKEND_REQUEST_FAILED,
    SESSION_STATUS_CHANGED
}
